/**
 * Parameter definitions with validation rules, help text, and suggested values
 */

export interface ParameterDefinition {
  name: string;
  label: string;
  type: 'number' | 'select' | 'boolean';
  category: 'basic' | 'technical' | 'fundamental' | 'options' | 'filters';
  helpText: string;
  suggestedValue?: string;
  min?: number;
  max?: number;
  step?: number;
  options?: { value: string; label: string }[];
  unit?: string;
  appliesToAssetTypes?: ('stock' | 'option')[];
}

export const STOCK_PARAMETERS: Record<string, ParameterDefinition> = {
  // Basic Filters
  minPrice: {
    name: 'minPrice',
    label: 'Min Price',
    type: 'number',
    category: 'basic',
    helpText: 'Minimum stock price. Good for filtering out penny stocks. Suggested: $5+ to avoid highly volatile low-priced stocks.',
    suggestedValue: '$5 - $10',
    min: 0.01,
    max: 100000,
    step: 0.01,
    unit: '$',
    appliesToAssetTypes: ['stock'],
  },
  maxPrice: {
    name: 'maxPrice',
    label: 'Max Price',
    type: 'number',
    category: 'basic',
    helpText: 'Maximum stock price. Useful for capital-limited strategies. Suggested: $100-$500 for manageable position sizes.',
    suggestedValue: '$100 - $500',
    min: 0.01,
    max: 100000,
    step: 0.01,
    unit: '$',
    appliesToAssetTypes: ['stock'],
  },
  minVolume: {
    name: 'minVolume',
    label: 'Min Daily Volume',
    type: 'number',
    category: 'basic',
    helpText: 'Minimum average daily trading volume. Higher volume = better liquidity. Suggested: 500,000+ for easy entry/exit, 1M+ for day trading.',
    suggestedValue: '500K - 1M+',
    min: 1,
    max: 1000000000,
    step: 1000,
    unit: 'shares',
    appliesToAssetTypes: ['stock'],
  },
  maxVolume: {
    name: 'maxVolume',
    label: 'Max Daily Volume',
    type: 'number',
    category: 'basic',
    helpText: 'Maximum average daily trading volume. Can help filter out mega-cap stocks if targeting smaller companies.',
    suggestedValue: 'Optional',
    min: 1,
    max: 1000000000,
    step: 1000,
    unit: 'shares',
    appliesToAssetTypes: ['stock'],
  },

  // Market Cap Filters
  minMarketCap: {
    name: 'minMarketCap',
    label: 'Min Market Cap',
    type: 'number',
    category: 'fundamental',
    helpText: 'Minimum market capitalization in millions. Small-cap: <$2B, Mid-cap: $2B-$10B, Large-cap: >$10B. Suggested: $1B+ for stability.',
    suggestedValue: '$1B+ for stability',
    min: 1,
    max: 10000000,
    step: 100,
    unit: '$M',
    appliesToAssetTypes: ['stock'],
  },
  maxMarketCap: {
    name: 'maxMarketCap',
    label: 'Max Market Cap',
    type: 'number',
    category: 'fundamental',
    helpText: 'Maximum market capitalization in millions. Useful for targeting small/mid-cap growth opportunities.',
    suggestedValue: 'Optional',
    min: 1,
    max: 10000000,
    step: 100,
    unit: '$M',
    appliesToAssetTypes: ['stock'],
  },

  // Fundamental Ratios
  minPERatio: {
    name: 'minPERatio',
    label: 'Min P/E Ratio',
    type: 'number',
    category: 'fundamental',
    helpText: 'Minimum Price-to-Earnings ratio. Lower = potentially undervalued. Suggested: 10-15 for value investing. Avoid negative P/E (unprofitable).',
    suggestedValue: '10-15 for value',
    min: -1000,
    max: 1000,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  maxPERatio: {
    name: 'maxPERatio',
    label: 'Max P/E Ratio',
    type: 'number',
    category: 'fundamental',
    helpText: 'Maximum Price-to-Earnings ratio. Lower = better value. Suggested: <20 for value stocks, <30 for growth. S&P 500 avg ~18-22.',
    suggestedValue: '<20 value, <30 growth',
    min: -1000,
    max: 1000,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  minPBRatio: {
    name: 'minPBRatio',
    label: 'Min P/B Ratio',
    type: 'number',
    category: 'fundamental',
    helpText: 'Minimum Price-to-Book ratio. Compares stock price to book value. Suggested: 0.5+ to avoid distressed companies.',
    suggestedValue: '0.5+',
    min: 0,
    max: 100,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  maxPBRatio: {
    name: 'maxPBRatio',
    label: 'Max P/B Ratio',
    type: 'number',
    category: 'fundamental',
    helpText: 'Maximum Price-to-Book ratio. <1 = trading below book value (potential value). Suggested: <1 for deep value, <3 for balanced.',
    suggestedValue: '<1 value, <3 balanced',
    min: 0,
    max: 100,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  minCurrentRatio: {
    name: 'minCurrentRatio',
    label: 'Min Current Ratio',
    type: 'number',
    category: 'fundamental',
    helpText: 'Minimum Current Ratio (current assets / current liabilities). Measures short-term liquidity. Suggested: ≥1.0 for healthy companies, ≥1.5 for safety.',
    suggestedValue: '≥1.0 healthy, ≥1.5 safe',
    min: 0,
    max: 100,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  maxCurrentRatio: {
    name: 'maxCurrentRatio',
    label: 'Max Current Ratio',
    type: 'number',
    category: 'fundamental',
    helpText: 'Maximum Current Ratio. Very high ratios (>3) may indicate inefficient asset use. Suggested: <3 for efficient operations.',
    suggestedValue: '<3',
    min: 0,
    max: 100,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  minQuickRatio: {
    name: 'minQuickRatio',
    label: 'Min Quick Ratio',
    type: 'number',
    category: 'fundamental',
    helpText: 'Minimum Quick Ratio (acid test). Like current ratio but excludes inventory. More conservative liquidity measure. Suggested: ≥1.0 for financial health.',
    suggestedValue: '≥1.0',
    min: 0,
    max: 100,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  maxDebtToEquity: {
    name: 'maxDebtToEquity',
    label: 'Max D/E Ratio',
    type: 'number',
    category: 'fundamental',
    helpText: 'Maximum Debt-to-Equity ratio. Measures financial leverage. Lower = less debt. Suggested: <1.0 for conservative, <2.0 for moderate risk.',
    suggestedValue: '<1.0 conservative',
    min: 0,
    max: 100,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  minROE: {
    name: 'minROE',
    label: 'Min ROE',
    type: 'number',
    category: 'fundamental',
    helpText: 'Minimum Return on Equity (%). Measures profitability vs shareholders\' equity. Suggested: ≥15% for quality companies, ≥20% for excellent.',
    suggestedValue: '≥15% good, ≥20% excellent',
    min: -100,
    max: 1000,
    step: 1,
    unit: '%',
    appliesToAssetTypes: ['stock'],
  },
  minROA: {
    name: 'minROA',
    label: 'Min ROA',
    type: 'number',
    category: 'fundamental',
    helpText: 'Minimum Return on Assets (%). Measures profitability vs total assets. Suggested: ≥5% for decent efficiency, ≥10% for excellent.',
    suggestedValue: '≥5% decent, ≥10% excellent',
    min: -100,
    max: 1000,
    step: 1,
    unit: '%',
    appliesToAssetTypes: ['stock'],
  },
  minDividendYield: {
    name: 'minDividendYield',
    label: 'Min Dividend Yield',
    type: 'number',
    category: 'fundamental',
    helpText: 'Minimum dividend yield (%). For income investing. Suggested: ≥2% for income, ≥4% for high yield. S&P 500 avg ~1.5-2%.',
    suggestedValue: '≥2% income, ≥4% high',
    min: 0,
    max: 100,
    step: 0.1,
    unit: '%',
    appliesToAssetTypes: ['stock'],
  },
  maxDividendYield: {
    name: 'maxDividendYield',
    label: 'Max Dividend Yield',
    type: 'number',
    category: 'fundamental',
    helpText: 'Maximum dividend yield (%). Very high yields (>8%) may signal risk. Suggested: <8% to avoid dividend traps.',
    suggestedValue: '<8%',
    min: 0,
    max: 100,
    step: 0.1,
    unit: '%',
    appliesToAssetTypes: ['stock'],
  },

  // Technical Indicators
  minRSI: {
    name: 'minRSI',
    label: 'Min RSI',
    type: 'number',
    category: 'technical',
    helpText: 'Minimum Relative Strength Index (0-100). Measures momentum. <30 = oversold (potential buy). Suggested: 30-40 for bounce plays.',
    suggestedValue: '30-40 for oversold',
    min: 0,
    max: 100,
    step: 1,
    appliesToAssetTypes: ['stock'],
  },
  maxRSI: {
    name: 'maxRSI',
    label: 'Max RSI',
    type: 'number',
    category: 'technical',
    helpText: 'Maximum Relative Strength Index (0-100). >70 = overbought. Suggested: <70 to avoid overextended stocks, <50 for conservative.',
    suggestedValue: '<70',
    min: 0,
    max: 100,
    step: 1,
    appliesToAssetTypes: ['stock'],
  },
  minPercentChange: {
    name: 'minPercentChange',
    label: 'Min % Change (1D)',
    type: 'number',
    category: 'technical',
    helpText: 'Minimum 1-day percent change. For momentum plays. Suggested: +2% for mild momentum, +5% for strong momentum.',
    suggestedValue: '+2% mild, +5% strong',
    min: -100,
    max: 1000,
    step: 0.1,
    unit: '%',
    appliesToAssetTypes: ['stock'],
  },
  maxPercentChange: {
    name: 'maxPercentChange',
    label: 'Max % Change (1D)',
    type: 'number',
    category: 'technical',
    helpText: 'Maximum 1-day percent change. To filter out extreme volatility. Suggested: <15% to avoid pump-and-dump patterns.',
    suggestedValue: '<15%',
    min: -100,
    max: 1000,
    step: 0.1,
    unit: '%',
    appliesToAssetTypes: ['stock'],
  },
  minBeta: {
    name: 'minBeta',
    label: 'Min Beta',
    type: 'number',
    category: 'technical',
    helpText: 'Minimum Beta (volatility vs market). Beta=1 means moves with market. >1 = more volatile. Suggested: 0.8-1.2 for balanced.',
    suggestedValue: '0.8-1.2',
    min: -10,
    max: 10,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },
  maxBeta: {
    name: 'maxBeta',
    label: 'Max Beta',
    type: 'number',
    category: 'technical',
    helpText: 'Maximum Beta. Lower beta = less volatile. Suggested: <1.5 for conservative, <2.0 for moderate risk.',
    suggestedValue: '<1.5 conservative',
    min: -10,
    max: 10,
    step: 0.1,
    appliesToAssetTypes: ['stock'],
  },

  // Geographic & Sector Filters
  country: {
    name: 'country',
    label: 'Country',
    type: 'select',
    category: 'filters',
    helpText: 'Filter by country/region. "US" for US-based companies only. Suggested: US for familiarity and regulatory safety.',
    suggestedValue: 'US for safety',
    options: [
      { value: '', label: 'All Countries' },
      { value: 'US', label: 'United States' },
      { value: 'CA', label: 'Canada' },
      { value: 'GB', label: 'United Kingdom' },
      { value: 'JP', label: 'Japan' },
      { value: 'CN', label: 'China' },
      { value: 'DE', label: 'Germany' },
      { value: 'FR', label: 'France' },
    ],
    appliesToAssetTypes: ['stock'],
  },
  sector: {
    name: 'sector',
    label: 'Sector',
    type: 'select',
    category: 'filters',
    helpText: 'Filter by sector/industry. Helps focus on specific market segments you understand.',
    options: [
      { value: '', label: 'All Sectors' },
      { value: 'technology', label: 'Technology' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'financials', label: 'Financials' },
      { value: 'consumer_cyclical', label: 'Consumer Cyclical' },
      { value: 'consumer_defensive', label: 'Consumer Defensive' },
      { value: 'industrials', label: 'Industrials' },
      { value: 'energy', label: 'Energy' },
      { value: 'utilities', label: 'Utilities' },
      { value: 'real_estate', label: 'Real Estate' },
      { value: 'materials', label: 'Materials' },
      { value: 'communication_services', label: 'Communication Services' },
    ],
    appliesToAssetTypes: ['stock'],
  },
};

export const OPTION_PARAMETERS: Record<string, ParameterDefinition> = {
  // Option-Specific Parameters
  optionType: {
    name: 'optionType',
    label: 'Option Type',
    type: 'select',
    category: 'options',
    helpText: 'Call options = right to buy (bullish). Put options = right to sell (bearish).',
    suggestedValue: 'Calls for bullish',
    options: [
      { value: 'call', label: 'Call' },
      { value: 'put', label: 'Put' },
    ],
    appliesToAssetTypes: ['option'],
  },
  expirationMinDays: {
    name: 'expirationMinDays',
    label: 'Min Days to Expiration',
    type: 'number',
    category: 'options',
    helpText: 'Minimum days until option expires. More time = more premium but safer. Suggested: 30+ days to avoid rapid theta decay.',
    suggestedValue: '30-45 days',
    min: 0,
    max: 730,
    step: 1,
    unit: 'days',
    appliesToAssetTypes: ['option'],
  },
  expirationMaxDays: {
    name: 'expirationMaxDays',
    label: 'Max Days to Expiration',
    type: 'number',
    category: 'options',
    helpText: 'Maximum days until option expires. Shorter = cheaper but riskier. Suggested: 30-90 days for balanced risk/reward.',
    suggestedValue: '30-90 days',
    min: 0,
    max: 730,
    step: 1,
    unit: 'days',
    appliesToAssetTypes: ['option'],
  },
  minStrike: {
    name: 'minStrike',
    label: 'Min Strike Price',
    type: 'number',
    category: 'options',
    helpText: 'Minimum strike price. Use to filter by absolute price level.',
    min: 0.01,
    max: 100000,
    step: 0.5,
    unit: '$',
    appliesToAssetTypes: ['option'],
  },
  maxStrike: {
    name: 'maxStrike',
    label: 'Max Strike Price',
    type: 'number',
    category: 'options',
    helpText: 'Maximum strike price. Use to filter by absolute price level.',
    min: 0.01,
    max: 100000,
    step: 0.5,
    unit: '$',
    appliesToAssetTypes: ['option'],
  },
  minMoneyness: {
    name: 'minMoneyness',
    label: 'Min Moneyness',
    type: 'number',
    category: 'options',
    helpText: 'Minimum moneyness % (strike/spot). <95% = ITM, 95-105% = ATM, >105% = OTM. Suggested: 95-105% for ATM options.',
    suggestedValue: '95-105% ATM',
    min: 0,
    max: 200,
    step: 1,
    unit: '%',
    appliesToAssetTypes: ['option'],
  },
  maxMoneyness: {
    name: 'maxMoneyness',
    label: 'Max Moneyness',
    type: 'number',
    category: 'options',
    helpText: 'Maximum moneyness %. OTM options are cheaper but riskier. Suggested: <120% to avoid deep OTM.',
    suggestedValue: '<120%',
    min: 0,
    max: 200,
    step: 1,
    unit: '%',
    appliesToAssetTypes: ['option'],
  },

  // Greeks
  deltaMin: {
    name: 'deltaMin',
    label: 'Min Delta',
    type: 'number',
    category: 'options',
    helpText: 'Minimum delta (0-1 for calls, -1-0 for puts). Measures price sensitivity to underlying. Suggested: 0.5+ for calls (50+ delta), -0.5 or lower for puts.',
    suggestedValue: '0.5+ for calls',
    min: -1,
    max: 1,
    step: 0.01,
    appliesToAssetTypes: ['option'],
  },
  deltaMax: {
    name: 'deltaMax',
    label: 'Max Delta',
    type: 'number',
    category: 'options',
    helpText: 'Maximum delta. Higher delta = more sensitive to price moves. Suggested: 0.7-0.8 for calls to balance risk/reward.',
    suggestedValue: '0.7-0.8',
    min: -1,
    max: 1,
    step: 0.01,
    appliesToAssetTypes: ['option'],
  },
  gammaMin: {
    name: 'gammaMin',
    label: 'Min Gamma',
    type: 'number',
    category: 'options',
    helpText: 'Minimum gamma. Measures delta change rate. Higher gamma = delta changes faster. ATM options have highest gamma.',
    min: 0,
    max: 1,
    step: 0.001,
    appliesToAssetTypes: ['option'],
  },
  thetaMax: {
    name: 'thetaMax',
    label: 'Max Theta (abs)',
    type: 'number',
    category: 'options',
    helpText: 'Maximum theta (time decay per day). Negative for buyers. Lower absolute value = less daily decay. Suggested: Minimize for long positions.',
    suggestedValue: 'Minimize for long',
    min: 0,
    max: 10,
    step: 0.01,
    appliesToAssetTypes: ['option'],
  },
  vegaMin: {
    name: 'vegaMin',
    label: 'Min Vega',
    type: 'number',
    category: 'options',
    helpText: 'Minimum vega. Measures IV sensitivity. Higher vega = more profit from IV increase. Good for volatility plays.',
    min: 0,
    max: 10,
    step: 0.01,
    appliesToAssetTypes: ['option'],
  },
  impliedVolatilityMin: {
    name: 'impliedVolatilityMin',
    label: 'Min IV',
    type: 'number',
    category: 'options',
    helpText: 'Minimum implied volatility (%). Higher IV = higher option prices. Suggested: 20-40% for normal conditions.',
    suggestedValue: '20-40% normal',
    min: 0,
    max: 500,
    step: 1,
    unit: '%',
    appliesToAssetTypes: ['option'],
  },
  impliedVolatilityMax: {
    name: 'impliedVolatilityMax',
    label: 'Max IV',
    type: 'number',
    category: 'options',
    helpText: 'Maximum implied volatility (%). Lower IV = cheaper options. Very high IV (>100%) signals extreme uncertainty.',
    suggestedValue: '<80%',
    min: 0,
    max: 500,
    step: 1,
    unit: '%',
    appliesToAssetTypes: ['option'],
  },
  openInterestMin: {
    name: 'openInterestMin',
    label: 'Min Open Interest',
    type: 'number',
    category: 'options',
    helpText: 'Minimum open interest (contracts). Measures liquidity. Suggested: 100+ for easy trading, 1000+ for active trading.',
    suggestedValue: '100+ minimum',
    min: 0,
    max: 1000000,
    step: 10,
    unit: 'contracts',
    appliesToAssetTypes: ['option'],
  },
  volumeMin: {
    name: 'volumeMin',
    label: 'Min Volume',
    type: 'number',
    category: 'options',
    helpText: 'Minimum daily volume. Higher = better liquidity and tighter spreads. Suggested: 50+ for decent liquidity.',
    suggestedValue: '50+',
    min: 0,
    max: 1000000,
    step: 10,
    unit: 'contracts',
    appliesToAssetTypes: ['option'],
  },
};

// Default screening profiles
export const DEFAULT_PROFILES = {
  valueStocks: {
    name: 'Value Stocks (Conservative)',
    asset_type: 'stock',
    description: 'Conservative value investing focused on financial health and undervaluation',
    parameters: {
      minPrice: 5,
      maxPrice: 100,
      minVolume: 500000,
      minMarketCap: 1000, // $1B
      maxPERatio: 20,
      maxPBRatio: 1,
      minCurrentRatio: 1,
      maxCurrentRatio: 3,
      maxDebtToEquity: 1,
      minQuickRatio: 1,
      minROE: 15,
      country: 'US',
    },
  },
  growthStocks: {
    name: 'Growth Stocks',
    asset_type: 'stock',
    description: 'High-growth companies with strong fundamentals',
    parameters: {
      minPrice: 10,
      minVolume: 1000000,
      minMarketCap: 500, // $500M
      maxMarketCap: 50000, // $50B (mid-cap)
      minROE: 20,
      minROA: 10,
      maxDebtToEquity: 2,
      minPercentChange: 2,
      country: 'US',
    },
  },
  dividendStocks: {
    name: 'Dividend Income Stocks',
    asset_type: 'stock',
    description: 'Stable dividend-paying companies for income generation',
    parameters: {
      minPrice: 10,
      minVolume: 500000,
      minMarketCap: 2000, // $2B
      minDividendYield: 3,
      maxDividendYield: 8,
      minCurrentRatio: 1.5,
      maxDebtToEquity: 1.5,
      maxBeta: 1.2,
      country: 'US',
    },
  },
  momentumStocks: {
    name: 'Momentum Stocks',
    asset_type: 'stock',
    description: 'Stocks with strong recent price momentum',
    parameters: {
      minPrice: 5,
      minVolume: 1000000,
      minPercentChange: 5,
      maxPercentChange: 20,
      minRSI: 60,
      maxRSI: 80,
      minBeta: 1.2,
      country: 'US',
    },
  },
  highDeltaCalls: {
    name: 'High Delta Call Options',
    asset_type: 'option',
    description: 'In-the-money call options with high delta for stock-like exposure',
    parameters: {
      optionType: 'call',
      expirationMinDays: 30,
      expirationMaxDays: 90,
      deltaMin: 0.7,
      deltaMax: 0.9,
      minMoneyness: 85,
      maxMoneyness: 95,
      openInterestMin: 100,
      volumeMin: 50,
      impliedVolatilityMax: 80,
    },
  },
  atmCalls: {
    name: 'At-The-Money Calls',
    asset_type: 'option',
    description: 'Near-the-money calls with balanced risk/reward',
    parameters: {
      optionType: 'call',
      expirationMinDays: 30,
      expirationMaxDays: 60,
      deltaMin: 0.45,
      deltaMax: 0.55,
      minMoneyness: 98,
      maxMoneyness: 102,
      openInterestMin: 100,
      volumeMin: 50,
    },
  },
  protectivePuts: {
    name: 'Protective Puts',
    asset_type: 'option',
    description: 'Out-of-the-money puts for downside protection',
    parameters: {
      optionType: 'put',
      expirationMinDays: 30,
      expirationMaxDays: 90,
      deltaMin: -0.3,
      deltaMax: -0.1,
      minMoneyness: 90,
      maxMoneyness: 98,
      openInterestMin: 100,
      volumeMin: 20,
    },
  },
};
